export const LEVEL_MAPPER = ["A1", "A2", "B1", "B2", "C1", "C2"];

export const CATG_MAPPER: Array<string> = [
    "Nationalities and countries",
    "News, lifestyles and current affairs",
    "Education",
    "Ways of travelling",
    "Travel",
    "Shopping",
    "Health and body care",
    "Travel and services vocab",
    "Things in the town, shops and shopping",
    "Services",
    "Work and jobs",
    "Personal identification",
    "Personal information",
    "Hobbies and pastimes",
    "Free time, entertainment",
    "Leisure activities",
    "Film",
    "Media",
    "Collocation",
    "Language",
    "Books and literature",
    "Food and drink",
    "Objects and rooms",
    "Daily life",
    "Relations with other people",
    "Family life",
    "Places",
    "House and home, environment",
    "Arts",
    "Idiomatic expressions",
    "Clothes",
    "Holidays",
    "Colours",
    "Scientific development",
    "Weather",
    "Technical and legal language",
    "Dimensions",
    "Adjectives: personality, description, feelings",
    "Hobbies and lifestyles",
];

export const POS_MAPPER = {
    CC: "Coordinating conjunction",
    CD: "Cardinal number",
    DT: "Determiner",
    EX: "Existential there",
    FW: "Foreign word",
    IN: "Preposition or subordinating conjunction",
    JJ: "Adjective",
    JJR: "Adjective, comparative",
    JJS: "Adjective, superlative",
    LS: "List item marker",
    MD: "Modal",
    NN: "Noun, singular or mass",
    NNS: "Noun, plural",
    NNP: "Proper noun, singular",
    NNPS: "Proper noun, plural",
    PDT: "Predeterminer",
    POS: "Possessive ending",
    PRP: "Personal pronoun",
    PRP$: "Possessive pronoun",
    RB: "Adverb",
    RBR: "Adverb, comparative",
    RBS: "Adverb, superlative",
    RP: "Particle",
    SYM: "Symbol",
    TO: "To",
    UH: "Interjection",
    VB: "Verb, base form",
    VBD: "Verb, past tense",
    VBG: "Verb, gerund or present participle",
    VBN: "Verb, past participle",
    VBP: "Verb, non-3rd person singular present",
    VBZ: "Verb, 3rd person singular present",
    WDT: "Wh-determiner",
    WP: "Wh-pronoun",
    WP$: "Possessive wh-pronoun",
    WRB: "Wh-adverb",
};
